[package]
name = "fab"
version = "0.1.1"
authors = ["Michael Melanson <michael@michaelmelanson.net>"]
description = "The fabulous, aspirationally Make-compatible, fabricator of things."
license = "MIT"
homepage = "https://github.com/michaelmelanson/fab-rs"

[dependencies]
clap = "3.1"
